database:
    type: "sqlite3"
    connection: "test.db"
schemas:
    - "../etc/schema/gohan.json"
    - "../tests/test_schema.yaml"
address: ":19090"
document_root: "../etc/"
etcd:
    - "http://127.0.0.1:4001"
keystone:
    use_keystone: true
    fake: true
    auth_url: "http://localhost:19090/v2.0"
    user_name: "admin"
    tenant_name: "admin"
    password: "gohan"
cors: "*"

logging:
  stderr:
    enabled: false
    level: ERROR
