#!/bin/sh

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

APP_NAME="gohan"
CLI="${APP_NAME}"
APP_USER="gohan"
APP_GROUP="gohan"
APP_ETC="/etc/${APP_NAME}"
APP_CONFIG="${APP_ETC}/gohan.yaml"
APP_OPT="/opt/gohan"

# source debconf library
. /usr/share/debconf/confmodule

case "$1" in

  configure)
    mkdir -p ${APP_ETC}
    chown ${APP_USER}.${APP_GROUP} ${APP_ETC}
    [ -f ${APP_CONFIG} ] || cp -R /opt/gohan/etc/* ${APP_ETC}

    cp ${APP_OPT}/packager/gohan.conf /etc/init
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac