#######################################################
#  Gohan API Server example configuraion
######################################################

# database connection configuraion
database:
    # yaml, json, sqlite3 and mysql supported
    # yaml and json db is for schema development purpose
    type: "sqlite3"
    # connection string
    # it is file path for yaml, json and sqlite3 backend
    connection: "./example.db"
# schema path
schemas:
    - "../etc/schema/gohan.json"
    - "./example.yaml"

# listen address for gohan
address: ":9091"
tls:
    # browsers need to add exception as long as we use self-signed certificates
    # so lets leave it disabled for now
    enabled: false
    key_file: ./key.pem
    cert_file: ./cert.pem
# document root of gohan API server
# Note: only static and schema directoriy will be served
document_root: "."
# list of etcd backend servers
etcd:
    - "http://127.0.0.1:4001"
# keystone configuraion
keystone:
    use_keystone: true
    fake: true
    auth_url: "http://localhost:9091/v2.0"
    user_name: "admin"
    tenant_name: "admin"
    password: "gohan"
# CORS (Cross-origin resource sharing (CORS)) configuraion for javascript based client
cors: "*"

# allowed levels  "CRITICAL", "ERROR", "WARNING", "NOTICE", "INFO", "DEBUG",
logging:
    stderr:
        enabled: true
        level: INFO
    file:
        enabled: true
        level: INFO
        filename: ./gohan.log
